repos:
  - repo: local
    hooks:
      - id: fix-frontmatter-date
        name: Fix Frontmatter Date
        files: ^src/content/.*\.mdx$
        language: python
        entry: python .githooks/date_updater.py
        additional_dependencies: [python-frontmatter]
        pass_filenames: true
        stages: [pre-commit]
